---
- name: "Check if config directory exists"
  stat:
    path: "{{ predixy_config_directory }}"
  register: predixy_config_dir_check

- name: "Install predixy config files"
  template:
    src: "config/{{ item }}.j2"
    dest: "{{ predixy_config_directory }}/{{ item }}"
  when: predixy_config_dir_check.stat.exists == true
  with_items:
    - predixy.conf
    - cluster.conf
    - latency.conf
  notify:
    - reload daemon
    - restart predixy
